config/routes.rb
Puzzler::Application.routes.draw do
  resources :nonograms
  match 'nonograms/image' => 'nonograms#image', :via => :post

  root :to => 'home#index', :via => :get
end

app/models/nonogram.rb
class NonogramDataValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, value)
    # validates the height dimension of the array
    unless value.map{ |e| e.length }.uniq.length == 1
      record.errors[attribute] << 'is malformed. The nested arrays have varying amounts of elements!'
    end

    # validates width & height ranges
    unless record.from_image
      unless (5..50).step(5).include?(record.width) && (5..50).step(5).include?(record.height)
        record.errors[attribute] << 'width & height must be a multiple of 5, between 5 & 50'
      end
    end
  end
end

class Nonogram
  include Mongoid::Document
  include Mongoid::Timestamps
  field :name
  field :data, :type => Array, :default => [[]]
  field :from_image, :type => Boolean, :default => false

  attr_accessible :name, :data, :from_image

  validates :name, :presence => true
  validates :data, :nonogram_data => true

  def width
    data[0].length
  end

  def height
    data.length
  end

  # calculates the clues based on the puzzle data
  def clues
    {
      :row => calculate_clues(data),
      :col => calculate_clues(data.transpose)
    }
  end

  private

  def calculate_clues array
    clue_array = []
    array.each do |e|
      a = []
      count = 0
      current_cell = nil
      e.each do |c|
        current_cell = c
        if c == 0
          a << count if count > 0
          count = 0
        else
          count += 1
        end
      end
      a << count if count > 0 && current_cell == 1
      clue_array << a
    end
    clue_array
  end

  # class methods
  def self.convert_js_data js_data
    new_array = []
    js_data.each do |col, row_array|
      new_array << row_array.map{ |e| e.to_i }
    end
    new_array
  end
end

app/controllers/application_controller.rb
require 'pp'

class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/nonograms_controller.rb
class NonogramsController < ApplicationController
  def index
    @nonograms = Nonogram.all
  end

  def show
    @nonogram = Nonogram.find params[:id]
    @clues = @nonogram.clues
  end

  def new
    @nonogram = Nonogram.new
  end

  def create
    @nonogram = Nonogram.new params[:nonogram]
    @nonogram.data = Nonogram.convert_js_data params[:data]
  end

  def edit
    @nonogram = Nonogram.find params[:id]
  end

  def update
    @nonogram = Nonogram.find params[:id]
    @nonogram.update_attributes params[:nonogram]
    @nonogram.data = Nonogram.convert_js_data params[:data]
  end

  def destroy
    @nonogram = Nonogram.find params[:id]
    @nonogram.destroy

    redirect_to nonograms_path
  end

  def image
    tmp = params[:nonogram][:image]
    img = Magick::Image.read(tmp.tempfile.path).first
    new_image = img.resize_to_fit(50, 50).threshold(Magick::QuantumRange*0.9)

    pixel_array = []
    new_image.rows.times { |x| pixel_array << Array.new(new_image.columns, 0) }

    new_image.each_pixel do |pixel, col, row|
      cell_value = case pixel.to_color
      when 'white' then 0
      when 'black' then 1
      end
      pixel_array[row][col] = cell_value
    end
    @nonogram = Nonogram.new :name => tmp.original_filename, :data => pixel_array, :from_image => true

    if @nonogram.save
      flash[:success] = 'Image converted!'
      redirect_to edit_nonogram_path(@nonogram)
    else
      flash[:error] = 'Image could not be converted.'
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  ACTION_MAP = {
    :update => :edit,
    :create => :new
  }.wia

  # renders a custom class for the body element for better scoping CSS
  def body_class
    [controller_name, ACTION_MAP[action_name] || action_name] * " "
  end

  def ascii string, *args
    options = args.extract_options!
    options.reverse_merge!({
        :font => Artii::Base.new().all_fonts.keys.sample
      })
    artii = Artii::Base.new(options) rescue Artii::Base.new() # for Artii bug
    ascii = artii.asciify(string)

    simple_format ascii, :class => 'ascii'
  end

  # includes view specific CSS & JS files
  #
  # for example, if the update action for the places controller is rendered,
  # it will look for the following files within the asset pipeline in a directory
  # called `/views`
  #
  # * places.[js|css]
  # * places_edit.[js|css]
  #
  # notice that the action it looks up for update is actually edit.  this mapping
  # is defined in the ACTION_MAP constant
  def view_asset type
    raise ArgumentError, 'type must be :css or :js' unless [:css, :js].include? type
    controller  = "views/#{controller_name}.#{type}"
    action      = "views/#{controller_name}_#{ACTION_MAP[action_name] || action_name}.#{type}"
    assets      = [(controller if Rails.application.assets[controller]), (action if Rails.application.assets[action])].compact
    return nil if assets.empty?

    case type
    when :css then stylesheet_link_tag *assets
    when :js  then javascript_include_tag *assets
    end
  end
end

# render flash messages
def render_flash
  html = ''
  flash.each{ |type, msg| html << content_tag(:div, msg, :class => type) }
  html.html_safe
end

app/views/home/index.html.haml
%ul.nav.nav-tabs.nav-stacked
  %li= link_to "Nonograms", nonograms_path

app/views/layouts/_validation_errors.html.haml
-if object.errors.any?
  #error_explanation
    %h2= "#{pluralize(object.errors.count, "error")} prohibited this #{object.class.name.downcase} from being saved:"
    %ul
      - object.errors.full_messages.each do |msg|
        %li= msg

app/views/layouts/application.html.haml
!!! 5
%html{ :lang => 'en' }
  %head
    %title PUZZLER
    = stylesheet_link_tag :application
    = yield :css
    = javascript_include_tag :application
    = view_asset :js
    = yield :js
    = csrf_meta_tags
  %body{ :class => body_class }
    .header= link_to ascii("PUZZLER"), root_path
    .flash= render_flash
    .content
      = yield

app/views/nonograms/edit.html.haml
:javascript
  var cellStatus = "#{@nonogram.data.to_json}";
  var nonogramPath = "#{url_for @nonogram}";

%ul.breadcrumb
  %li
    = link_to 'Home', root_path
    %span.divider= '|'
  %li
    = link_to 'Nonograms', nonograms_path
    %span.divider= '|'
  %li.active= 'Edit ' + @nonogram.name

.align-center
  .well.form-inline.container
    = simple_form_for @nonogram do |n|
      = n.input :name
    = button_tag 'Save', :id => :save, :class => 'btn btn-small btn-primary'
  %canvas#nonogram
    NOT SUPPORTED WITH THIS BROWSER

app/views/nonograms/index.html.haml
%h6.align-center
  To learn about nonograms, visit the wiki page
  = link_to 'here', 'http://en.wikipedia.org/wiki/Nonogram', :target => '_blank'

= link_to new_nonogram_path do
  .btn.btn-primary New Nonogram

%table.table
  %thead
    %tr
      %th Name
      %th
  %tbody
    - @nonograms.each do |nonogram|
      %tr.nonogram{:data => { :url => url_for(nonogram) }}
        %td
          = nonogram.name
          %span.dimensions= "(#{nonogram.width}x#{nonogram.height})"
        %td.align-right
          = link_to edit_nonogram_path(nonogram) do
            %button.btn{ :title => 'Edit'}
              %i.icon-edit
          = link_to nonogram, :method => :delete, :data => { :confirm => "Are you sure you want to delete #{nonogram.name}?" } do
            %button.btn{ :title => 'Delete'}
              %i.icon-remove

app/views/nonograms/new.html.haml
:javascript
  var nonogramsPath = "#{nonograms_path}"
- size_options = (5..50).step(5)

%ul.breadcrumb
  %li
    = link_to 'Home', root_path
    %span.divider= '|'
  %li
    = link_to 'Nonograms', nonograms_path
    %span.divider= '|'
  %li.active= 'New Nonogram'

.align-center
  .well.form-inline.container
    .row
      .span6
        %h4 Convert an image
        = render 'layouts/validation_errors', :object => @nonogram
        = simple_form_for :nonogram, :url => nonograms_image_path, :multipart => true do |f|
          %h6 Images get resized to no bigger than 50 pixels and converted to 2 colors (black & white) so don't expect much!  Use simple images with a good balance of dark and light.  Anything mostly white will be near impossible, and anything too dark will be too easy.  Line drawings work best.
          = f.input :image, :as => :file, :required => false
          = f.submit 'Convert Image', :class => 'btn btn-info'
      .span6
        %h4 Or draw your own!
        %h6 Changing the size of the board, will clear all cells!
        %div
          = label_tag :nonogram_width, 'Width'
          = select_tag :nonogram_width, options_from_collection_for_select(size_options, :to_s, :to_s, 20)
          = label_tag :nonogram_height, 'Height'
          = select_tag :nonogram_height, options_from_collection_for_select(size_options, :to_s, :to_s, 10)
        %br
        = simple_form_for @nonogram do |n|
          = n.input :name
        = button_tag 'Save', :id => :save, :class => 'btn btn-small btn-primary'
  %canvas#nonogram
    NOT SUPPORTED WITH THIS BROWSER

app/views/nonograms/show.html.haml
:javascript
  var nonogram_id = '#{@nonogram.id}';
  var nonogram_name = '#{@nonogram.name}';
  var cell_status = '#{@nonogram.data.to_json}';

%ul.breadcrumb
  %li
    = link_to 'Home', root_path
    %span.divider= '|'
  %li
    = link_to 'Nonograms', nonograms_path
    %span.divider= '|'
  %li.active.name ???

.well.form-inline.align-center
  = button_tag 'Save Progress', :id => :save, :class => 'btn btn-small btn-primary'
  = button_tag 'Check for Errors', :id => :error_check, :class => 'btn btn-small btn-info'
  = button_tag 'Reset', :id => :reset, :class => 'btn btn-small btn-warning'

%table.master
  %tr
    %td
    %td.col_clues
      %table
        %tr
          - @clues[:col].each do |col|
            %td
              - col.each do |clue|
                %span.clue= clue
  %tr
    %td.row_clues
      %table
        - @clues[:row].each do |row|
          %tr
            %td
              - row.each do |clue|
                %span.clue= clue
    %td.canvas
      %canvas#nonogram